README.md
rpi2-gen-image.sh

Fixed DEFLOCAL shell var substitution while sed-ing /etc/locale.gen

---

rpi2-gen-image.sh

git-core is a transitional package since April 2010 and the no more
supported Debian 6 Squeeze.
This makes rpi2-gen-image stop pulling in ancient and obsolete transitional packages onto people's systems.

Use package git instead of git-core: Don't pull in obsolete packages

---

rpi23-gen-image.sh

Currently the script always requires the apt lock to be free even if there are no packages to install on the build system. Although the script correctly detects missing packages, it still ends up calling :
apt-get -qq -y install ${REQUIRED_PACKAGES}
in every case, even when all required packages are already installed.
This unfortunately makes the script fail when another apt operation is running, even when there’s no package missing for the build.
This patch relaxes the dependency on the apt lock, by only doing the apt… install when there are actual missing packages to install.

Don’t require apt lock to be available on build machine if there are no packages to install

---

README.md
rpi23-gen-image.sh

While running rpi23-gen-image inside a chroot, it tripped over a missing dbus-uuidgen binary.

Fixed: require dbus package as we use dbus-uuidgen

---

README.md
rpi23-gen-image.sh

BASEDIR and IMAGE_NAME parameters allows me to build some images in parallel and save the result files to different paths, ex:
`
BASEDIR=/var/workspace/1 IMAGE_FILENAME=/var/images/1 ./rpi23-gen-image.sh
`
`
BASEDIR=/var/workspace/2 IMAGE_FILENAME=/var/images/2 ./rpi23-gen-image.sh
`

Add BASEDIR and IMAGE_NAME

---

bootstrap.d/10-bootstrap.sh

Since the release of Debian Stretch, the apt and apt-get commands run as the unprivileged user _apt.  With the permissions of the qemu-arm-static binary set to 644, the _apt user cannot execute commands and the script will fail when executing apt-get in the chroot environment.  
Relevant portions of the script output below:
```
+ chroot_exec apt-get -qq -y update
+ LANG=C LC_ALL=C DEBIAN_FRONTEND=noninteractive chroot /home/justin/rpi/rpi23-gen-image/images/stretch/build/chroot apt-get -qq -y update
W: GPG error: http://security.debian.org stretch/updates InRelease: Couldn't execute /usr/bin/apt-key to check /var/lib/apt/lists/partial/security.debian.org_dists_stretch_updates_InRelease
W: The repository 'http://security.debian.org stretch/updates InRelease' is not signed.
W: GPG error: …
```

Apt-get in Chroot Environment Causes Script to Fail

---

README.md
bootstrap.d/11-apt.sh

The option is useful for packages where debootstrap fail, for example packages with pre-dependencies.

Added new option APT_INCLUDES_LATE for installing packages using apt.

---

bootstrap.d/13-kernel.sh
bootstrap.d/15-rpi-config.sh
bootstrap.d/20-networking.sh
bootstrap.d/41-uboot.sh
bootstrap.d/42-fbturbo.sh
functions.sh

This is useful when using libpam-tmpdir to replace the environment to avoid non-working paths in chroot.

Introduce as_nobody() function to make it easier to control how it is done.

---

README.md
rpi23-gen-image.sh

arm64-specific defaults are:
```
KERNEL_IMAGE=kernel8.img
KERNEL_BIN_IMAGE=Image
KERNEL_DEFCONFIG=bcmrpi3_defconfig
QEMU_BINARY=/usr/bin/qemu-aarch64-static
```

set better defaults for arm64 builds

---

bootstrap.d/13-kernel.sh
rpi23-gen-image.sh

First commit : 
* Syntax error on the use of wildcard *  in the mv command
* option -u used twice in git command
Second Commit (buster only) : 
* removed apt-transport-https that has disappeared from repositories
This last change induces  errors with seccomp, (syscall 383 in 32 bit and syscall 277 in 64bit) 277 freezes the operations in apt script.

Proposed amendments  of 13-kernel.sh

---

rpi23-gen-image.sh

With newer systemd builds, systemd-networkd does not boot anymore, leading to the network being disabled. Installing libnss-systemd resolves this problem, but it is not available on Jessie systems.
The error this PR aims to resolve:
```
Jul 01 08:58:09 foo systemd-networkd[563]: Cannot resolve user name systemd-network: No such process
Jul 01 08:58:10 foo systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
Jul 01 08:58:10 foo systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.```

Fix networking with systemd

---

README-CN.md
README.md
rpi23-gen-image.sh

This only leaves unencrypted/unverified:
- All Debian mirrors (no security problem, since apt verifies everything)
- The EmDebian repository in the README (nasty, since even the repository key is fetched over an untrusted connection)

Change every URL to https

---

README-CN.md
README.md
templates/rpi3-stretch-arm64-4.14.y

4.14.y is used as default kernel version of many distros. Additionnaly the 4.14.y branch is the current default branch of the RPi kernel repo.

Use 4.14.y as default kernel version

---

bootstrap.d/11-apt.sh

Hi!
When I set `APT_INCLUDES_LATE` to a comma-separated list of packages `apt-get install` failed, because it treats the package list as single argument. 
`APT_INCLUDES_LATE=net-tools,vim,mc,git,systemd-sysv,tmux,wpasupplicant,ufw`
Output before my fix:
```
+ [ net-tools,vim,mc,git,systemd-sysv,tmux,wpasupplicant,ufw ]
+ echo net-tools,vim,mc,git,systemd-sysv,tmux,wpasupplicant,ufw
+ tr ,  
+ chroot_exec apt-get -qq -y install net-tools vim mc git systemd-sysv tmux wpasupplicant ufw
+ LANG=C LC_ALL=C DEBIAN_FRONTEND=noninteractive chroot /root/rpi23-gen-image/images/stretch-custom/build/chroot apt-get -qq -y install net-tools vim mc git systemd-sysv tmux wpasupplicant ufw
E: Unable to locate package net-tools vim mc git systemd-sysv tmux wpasupplicant ufw
```
Output after my fix:
```
+ [ …
```

11-apt.sh: Fixed APT_INCLUDES_LATE

---

bootstrap.d/12-locale.sh

Hi!
I encountered a bug while bootstrapping Debian Stretch.
Setting the timezone to `Europe/Berlin` had no effect and `Etc/UTC` was still used.
This bug occurs when the package `tzdata` was upgraded during the execution of `11-apt.sh`.
Output of `11-apt.sh`:
```shellscript
+ . bootstrap.d/11-apt.sh
+ . ./functions.sh
+ [ -n http://127.0.0.1:3142/ ]
<snip>
+ chroot_exec apt-get -qq -y -u dist-upgrade
+ LANG=C LC_ALL=C DEBIAN_FRONTEND=noninteractive chroot /<snip>/build/chroot apt-get -qq -y -u dist-upgrade
<snip>
Preparing to unpack .../tzdata_2018i-0+deb9u1_all.deb ...
Unpacking tzdata (2018i-0+deb9u1) over (2018g-0+deb9u1) ...
Setting up tzdata (2018i-0+deb9u1) ...
Current default time zone: 'Etc/UTC'
Local time is now:      Thu Jan 24 09:56:24 UTC 2019.
Universal Time is now:  Thu Jan …
```

Fixed setting the timezone

---

bootstrap.d/11-apt.sh

Fix "Unable to find package" error thrown by apt-get if you put more than one package to `$APT_INCLUDES_LATE`

Fix late installing more than one package

---

README.md
bootstrap.d/11-apt.sh
bootstrap.d/13-kernel.sh
bootstrap.d/14-fstab.sh
bootstrap.d/15-rpi-config.sh
bootstrap.d/20-networking.sh
bootstrap.d/43-videocore.sh
bootstrap.d/44-nexmon_monitor_patch.sh
rpi23-gen-image.sh

RPI4
Debian Bullseye
Added and removed kernel options 
QEMU with 64bit kernel doenst fail anymore (didnt boot it up, but it compiled)
No more compile error on bluetooth firmware download
Kernel bump from 4.14 to 4.19
flex,bison and libssl-dev required to build kernel
https://github.com/drtyhlpr/rpi23-gen-image/issues/203
https://github.com/drtyhlpr/rpi23-gen-image/issues/196
copying vexpress arm32 version to arm64 works just fine
`/root/rpi23-gen-image/images/bullseye/qemu/2019-10-22-arm64-CURRENT-rpi3P-bullseye-arm64.qcow2 (16G) : successfully created`

PATCHES for:

---

bootstrap.d/15-rpi-config.sh
rpi23-gen-image.sh

Proposal to add copy of fixup4*  and start4* files from firmware repository 
into boot folder of the new image.
If these files are not present boot hangs at early stage.
Tested with buster and bullseye 64

fixup4*  and start4* files missing for Pi4 boot

---

bootstrap.d/11-apt.sh
bootstrap.d/13-kernel.sh
files/apt/sources.list

Removed deprecated mkknlimg see [kernel issue #3249](https://github.com/raspberrypi/linux/issues/3249)
change stretch to buster as stable
change buster to bullseye as testing
Signed-off-by: Gérard Vidal <gerard.vidal@ens-lyon.fr>

removed deprecated mkknlimg and mote to buster/bullseye

---

rpi23-gen-image.sh

The script creates a firmware partition of 64M.  Current size of kernel images, initrd and blobs is 40M, leaving insufficient space to do a package-managed kernel upgrade.  This PR increases the size to 128M, which allows the kernel to be package-managed, as long as one remembers to remove old versions after the fact.

increase firmware partition from 64M to 128M
